# Change these first
owner: scavin # Your GitHub organization or username, where this repository lives
repo: appinnuptime # The name of this repository

sites:
  - name: Appinn.com
    url: https://www.appinn.com
  - name: META.APPINN
    url: https://meta.appinn.net
  - name: Appinn Images Server(AIS)
    url: https://static1.appinn.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.appinn.com
  favicon: https://github.com/scavin/static_appinn/blob/master/apple-touch-icon-144x144.png?raw=true
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/scavin/static_appinn/blob/master/appinn-dark-logo.png?raw=true
  name: Hi
  introTitle: "小众软件的服务器还好吗？"
  introMessage: 这里是小众软件的服务器状态页面，用来看看她们还好吗？包括了：[小众软件](https://www.appinn.com/)、[小众软件论坛](https://meta.appinn.net)、[AIS](https://img3.appinn.net)
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
